### ISSUE TITLE
[windows] - always get code list of empty string

### ISSUE THREAD

**Issue by jscarl** [techkop3/read_barcode#1]
Hi, Thank you for created this amazing project.

Anyway is there any specification for scanner or additional configuration to use this project, I try to run the example is and the result like below, the QR is containing battery scanner data

> flutter: []
flutter: [, ]
flutter: [, , ]
flutter: [, , , ]
flutter: [, , , , ]
flutter: [, , , , , ]
flutter: [, , , , , , ]
flutter: [, , , , , , , ]
flutter: [, , , , , , , , ]
flutter: [, , , , , , , , , ]
flutter: [, , , , , , , , , , ]
flutter: [, , , , , , , , , , , ]
flutter: [, , , , , , , , , , , , ]
flutter: [, , , , , , , , , , , , , ]

**Comment by chetu-ko** [comment]
Hi @jscarl,
The package is for scan the barcode data but here you are using the QR data....

**Comment by fernandopc1996** [comment]
I had the same problem on windows

But changing lines 40 and 41 of

```
_keyController.sink.add(keyEvent.data.keyLabel);
 keycode.add(keyEvent.data.keyLabel.toString());`
```

For

```
_keyController.sink.add(keyEvent.data.logicalKey.keyLabel);
keycode.add(keyEvent.data.logicalKey.keyLabel.toString());
```

That way it works perfectly on windows and android.

I haven't tested it on other platforms. As I only have one model of scanner devices, I don't know if the problem is linked to my scanner.
Sorry for the writing. I do not speak english.
